name: attendance_app
description: For test purpose only on Hashmicro

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
